// UI LANGUAGE
export const UI_LANGUAGE_SET = "UI_LANGUAGE_SET";
// UI SIDEBAR
export const UI_SIDEBAR_OPEN = "UI_SIDEBAR_OPEN";
export const UI_SIDEBAR_CLOSE = "UI_SIDEBAR_CLOSE";
// UI MENU LINKS
export const UI_MUSEUM_LINKS_REQUEST = "UI_MUSEUM_LINKS_REQUEST";
export const UI_MUSEUM_LINKS_SUCCESS = "UI_MUSEUM_LINKS_SUCCESS";
export const UI_MUSEUM_LINKS_FAIL = "UI_MUSEUM_LINKS_FAIL";
